config/routes.rb
Rails.application.routes.draw do
  get 'accounts/show'

  root 'home#index'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'

  post '/signup', to: 'users#create'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :users
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	validates_uniqueness_of :email
	validates_presence_of :email, :password_digest
	has_secure_password
	has_one :account
	after_create :create_account

	def create_account
		Account.create(user_id: self.id, balance: 0.0)
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authorize

  def show
  	@account = current_user.account
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	# first time called @current_user is nil
  	# second time its called
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
  	redirect_to '/login' unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to accounts_show_path
  	else
  		redirect_to '/login'
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      session[:user_id] = @user.id
  		redirect_to accounts_show_path
  	else
  		render :new
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation)
  end



end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/show.html.erb
<%= link_to 'Logout', logout_path, method: :delete %>
<h3>Your balance is <%= @account.balance %> </h3>

app/views/home/index.html.erb
<h1>Welcome to the bank</h1>
<%= link_to 'Sign Up', signup_path %>
<%= link_to 'Login', login_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TenthBank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for :user do |f| %>
	<%= f.label :email %>
	<%= f.text_field :email %>

	<%=f.label :password %>
	<%= f.password_field :password %>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>

	<%= f.submit %>
<% end %>